INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Administração', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Agronomia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Antropologia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Arqueologia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Arquitetura', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Arquivística', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Artes Cênicas', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Artes Visuais', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Astronomia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Biblioteconomia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Bioengenharia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Biofísica', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Biologia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Biologia Marinha', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Biomedicina', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Botânica', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Ciência e Tecnologia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Ciência da Computação', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Ciência Política', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Ciências Agrárias', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Ciências Ambientais', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Ciências Atuariais', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Ciências Biológicas', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Ciências Biomoleculares', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Ciências Contábeis', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Ciências da Saúde', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Ciências do Meio Aquático', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Ciências Humanas', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Ciências Matemáticas da Terra', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Ciências Naturais', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Ciências Náuticas', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Ciências Sociais', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Cinema', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Comunicação social', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Dança', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Defesa e Gestão Estratégica Internacional', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Desenho Industrial', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Design de Interiores', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Design de Moda', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Direito', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Ecologia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Economia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Economia Doméstica', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Editoração', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Educação Artística', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Educação do Campo', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Educação física', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Enfermagem', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia Aeroespacial', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia Aeronáutica', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia Agrícola', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia Ambiental', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia Biomédica', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia Cartográfica', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia Civil', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia de Alimentos', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia de Computação', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia de Controle e Automação', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia de Manufatura', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia de Materiais', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia de Minas', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia de Pesca', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia de Petróleo', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia de Produção', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia de Sistemas Eletrônicos', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia de Software', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia de Tecidos', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia de Telecomunicações', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia Elétrica', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia Física', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia Florestal', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia Geológica', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia Industrial Madeireira', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia Mecânica', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia Mecatrônica', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia Metalúrgica', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia Militar', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia Naval e Oceânica', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia Nuclear', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia Química', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia Sanitária', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Engenharia Têxtil', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Escultura', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Estatística', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Farmácia (ou Bioquímica)', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Filosofia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Física', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Física Computacional', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Física Médica', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Fisioterapia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Fonoaudiologia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Gastronomia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Geofísica', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Geografia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Geologia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Geoprocessamento e Sensoriamento Remoto', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Gerontologia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Gestão Ambiental', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Gestão Pública', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Gravurismo', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'História', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'História da Arte', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Hotelaria', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Informática', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Informática Biomédica', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Jornalismo', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Letras', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Linguística', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Matemática', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Matemática Aplicada', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Matemática Computacional', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Medicina', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Medicina Veterinária', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Meteorologia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Microbiologia e Imunologia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Museologia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Música', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Nanotecnologia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Naturologia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Neurociência', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Nutrição', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Oceanografia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Odontologia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Ordenamento do Território', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Paisagismo', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Pedagogia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Pintura', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Produção Audiovisual', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Produção Cultural', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Psicologia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Publicidade e Propaganda', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Química', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Química Ambiental', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Química Industrial', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Quiropraxia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Relações Internacionais', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Relações Públicas', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Saúde Coletiva', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Segurança Pública', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Serviço Social', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Sistemas de Informação', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Sociologia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Teatro', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Teologia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Terapia ocupacional', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Transporte Terrestre', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Turismologia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Urbanismo', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Zootecnia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Cursos de tecnologias', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Agrimensura', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Agroecologia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Agroindústria', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Análise e Desenvolvimento de Sistemas', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Aquacultura', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Automação Industrial', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Biocombustíveis', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Biotecnologia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Cafeicultura', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Ciência dos Alimentos', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Ciência dos Materiais', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Ciências Aeronáuticas', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Comércio Exterior', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Construção de Edifícios', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Construção de Estradas', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Construção Naval', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Cooperativismo', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Cosmetologia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Design de Jogos Digitais', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Design de Produto', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Design Gráfico', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Drenagem e Irrigação', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Energias Renováveis', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Enologia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Esporte e Lazer', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Eventos', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Fotografia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Fruticultura', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Gestão Comercial', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Gestão da Qualidade', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Gestão da Tecnologia da Informação', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Gestão de Petróleo e Gás', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Gestão de Recursos Hídricos', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Gestão de Segurança Privada', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Gestão do Agronegócio', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Gestão em Serviços Jurídicos e Notariais', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Gestão Financeira', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Gestão Hospitalar', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Gestão Portuária', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Horticultura', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Logística', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Manutenção Industrial', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Mecatrônica e Mecânica de Precisão', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Meliponicultura', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Mercadologia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Mineração', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Negócios Imobiliários', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Oftálmica', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Processamento de Dados', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Processos Escolares', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Processos Metalúrgicos', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Produção de Aguardente', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Produção de Laticínios', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Produção de Materiais Plásticos', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Produção Fonográfica', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Produção Sucroalcooleira', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Produção Têxtil', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Projetos de Estruturas Aeronáuticas', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Radiologia', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Recursos Humanos', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Redes de Computadores', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Redes de Telecomunicações', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Saneamento Ambiental', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Secretariado', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Segurança da Informação', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Segurança no Trabalho', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Silvicultura', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Sistemas Biomédicos', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Sistemas de Navegação Fluvial', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Sistemas Elétricos', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Sistemas Embarcados', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Sistemas para Internet', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Telemática', 'Y');
INSERT INTO CURSO (id, curso_desc, active) values (CURSO_SEQ.NEXTVAL, 'Transporte Aéreo', 'Y');